services:
  svc_todo_app:
    image: todo_app:1.2
    container_name: todo_app
    ports:
      - "3000:3000"

  svc_mongo:
    image: mongo:latest
    container_name: mongoDb
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: todoDb

  svc_mongoExpress:
    image: mongo-express
    container_name: mongoUi
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@svc_mongo/


