# base image
FROM node:18-alpine

WORKDIR /TodoApp

COPY package*.json /TodoApp

# here we can run scripts with 'RUN' to install dependencies (if reqd.)
RUN npm install

# copy from 'host machine' to 'target dir in the container'.
## [used COPY because COPY executes on HOST machine and the files we need to copy are on the Host machine (this PC)]
COPY ./src ./src

EXPOSE 3000

# final entry command with 'CMD'
CMD ["node", "./src/app.js"]